### ISSUE TITLE
incorrect types or wrong order?

### ISSUE THREAD

**Issue by skywo1f** [byuflowlab/FLOWVLM#20]
I am trying to run the example notebook singlerotor.ipynb but I get this issue:

MethodError: no method matching generate_rotor(::Float64, ::Float64, ::Int64, ::InlineStrings.String31; data_path="C:\\Users\\dsfjk\\.julia\\packages\\FLOWUnsteady\\UtgRI\\src\\../data/", pitch=0.0, n=50, CW=true, ReD=940929.447536191, altReD=[5400.0, 0.0001, 1.7308435142352243e-5], verbose=true, xfoil=true, plot_disc=true)
Closest candidates are:
  generate_rotor(::Real, ::Real, ::Int64, !Matched::Matrix{Float64}, !Matched::Matrix{Float64}, !Matched::Matrix{Float64}, !Matched::Matrix{Float64}, !Matched::Vector{Tuple{Float64, Matrix{Float64}, String}}; data_path, read_polar, pitch, n, CW, blade_r, ReD, altReD, Matip, ncrit, xfoil, spline_k, spline_s, splines_s, spline_bc, turbine_flag, rfl_n_lower, rfl_n_upper, rediscretize_airfoils, verbose, verbose_xfoil, v_lvl, save_polars, save_polar_pref, plot_disc, figsize_factor) at C:\Users\dsfjk\.julia\packages\FLOWUnsteady\UtgRI\src\FLOWUnsteady_rotor.jl:30
  generate_rotor(::Real, ::Real, ::Int64, !Matched::Matrix{Float64}, !Matched::Matrix{Float64}, !Matched::Matrix{Float64}, !Matched::Matrix{Float64}, !Matched::Vector{Tuple{Float64, String, String}}; data_path, optargs...) at C:\Users\dsfjk\.julia\packages\FLOWUnsteady\UtgRI\src\FLOWUnsteady_rotor.jl:180
  generate_rotor(::Real, ::Real, ::Int64, !Matched::String; data_path, optargs...) at C:\Users\dsfjk\.julia\packages\FLOWUnsteady\UtgRI\src\FLOWUnsteady_rotor.jl:208

**Comment by EdoAlvarezR** [comment]
At the moment, example notebooks are not up to date with the latest version of FLOWUnsteady. To run this notebook, notice the date of the notebook and roll all dependency packages back to their status at such date.
